.github/.cspell/dart_dictionary.txt, packages/globe_cli/README.md
=> docs: Add CLI readme

docs.yaml, docs/frameworks/index.mdx, docs/frameworks/jaspr.mdx, docs/index.mdx, docs/infrastructure/cron-jobs.mdx, docs/infrastructure/index.mdx, docs/infrastructure/websockets.mdx
Added backend, frontend and flutter web in the home screen text
Removed cron jobs from docs sidebar and made the md file show a warning
Removed jaspr from docs sidebar, frameworks page and made the md file show a warning
=> docs: Update Content

CHANGELOG.md, packages/globe_cli/CHANGELOG.md, packages/globe_cli/lib/src/package_info.dart, packages/globe_cli/pubspec.yaml
=> chore(release): Publish globe_cli

.gitignore, packages/globe_cli/lib/src/commands/deploy_command.dart, packages/globe_cli/lib/src/commands/login_command.dart, packages/globe_cli/lib/src/utils/api.dart, packages/globe_cli/lib/src/utils/auth.dart, packages/globe_cli/lib/src/utils/prompts.dart, packages/globe_cli/test/login_test.dart
Added login with API tokens in cli with
```
globe login --token <token>
```
Added support for deploying with API tokens
```
globe deploy --token <token> --project <project_uuid>
```
=> feat(globe_cli): API token support for cli login and deploy

docs/index.mdx
The dart frog link directs to shelf's.
=> docs: Fix spelling and puctuation, fix dart_frog link

docs/infrastructure/limits.mdx
=> docs: Update limits documentation

packages/globe_cli/lib/src/commands/build_logs_command.dart
This happens when attempting to connect to globe event source with either invalid deployment or project ID.
=> fix: Handle event-source exception gracefully

packages/globe_cli/lib/src/commands/token/token_create_command.dart
Add validation for token expiry
=> fix: Token expiry validation

docs/infrastructure/cron-jobs.mdx
Fixed cron code to work as expected and added the link to the doc for cron code format that is supported in Globe.
=> docs: Fixed cron code and added doc link

docs/infrastructure/regions.mdx
=> docs: Update regions table

packages/globe_cli/lib/src/commands/token/token_create_command.dart, packages/globe_cli/lib/src/utils/api.dart
Add the default date (a year from now) to a token create prompt.
=> refactor: Add default expiry date

packages/globe_cli/lib/src/commands/deploy_command.dart, packages/globe_cli/lib/src/utils/api.dart, packages/globe_cli/lib/src/utils/logs.dart, packages/globe_cli/lib/src/utils/rpc.dart
=> refactor: Migrate to the latest realtime API

packages/globe_cli/analysis_options.yaml, packages/globe_cli/lib/src/utils/archiver.dart, packages/globe_cli/lib/src/utils/ignore.dart
Closes: #68 
Match `gitignore` patterns correctly.
=> fix: Rework gitignore matching

packages/globe_cli/lib/src/command_runner.dart, packages/globe_cli/lib/src/commands/deploy_command.dart, packages/globe_cli/lib/src/commands/project/project_pause_command.dart, packages/globe_cli/lib/src/commands/project/project_resume_command.dart, packages/globe_cli/lib/src/commands/project_command.dart, packages/globe_cli/lib/src/utils/api.dart, packages/globe_cli/lib/src/utils/scope.dart
Closes: https://github.com/orgs/invertase/projects/23/views/1?pane=issue&itemId=58000907
=> feat: Pause & resume project from CLI

packages/globe_cli/lib/src/commands/deploy_command.dart, packages/globe_cli/lib/src/commands/update.dart
Remove un-necessary dots. `.progress(message)` already internally attaches `...`.
=> fix: Remove unnecessary dots

packages/globe_cli/lib/src/utils/api.dart
This PR reflects REST API changes made during UI for token generation work.
=> refactor: Remove token generate usage

packages/globe_cli/lib/src/command_runner.dart, packages/globe_cli/lib/src/utils/prompts.dart
Resolves: [DartGlobe#505](https://github.com/invertase/dart_globe/issues/505)
=> chore: Allow passing `local` or api-url for globe cli

packages/globe_cli/lib/src/commands/create_project_command.dart
=> fix: PathNotFoundException when using templates

docs/infrastructure/limits.mdx
Update docs to reflect resources allocations for free plan.
=> chore: Increase resource limit for free plan

docs.json
Remove dead link on the sidebar
Remove link to initial release on the sidebar
=> docs: Remove dead link

packages/globe_cli/lib/src/commands/update.dart, packages/globe_cli/lib/src/package_info.dart
Fixes broken `globe update` due to wrong package name.
=> fix: Use actual package name

packages/globe_cli/lib/src/package_info.dart, packages/globe_cli/lib/src/utils/prompts.dart, packages/globe_cli/lib/src/utils/scope.dart
Fixed an issue where user is asked to Select Organization twice when `selectOrLinkNewScope` is called.
=> chore: Pass org if already selected

docs/deployments/environment-variables.mdx
A very minor typo correction was done by replacing "a specifically" with "specifically" in the environment-variables doc. I however think a better sentence would be 
`Enter the name and value of your variable. All values are encrypted and can only be viewed by explicitly accessing them on the dashboard. `
Let me know if I should proceed with this change only simply proceed with the typo correction.
=> docs: Correct typo in deployments/environment-variables page

docs/terms-privacy/privacy-policy.mdx
PostHog web analytics tracking requires a cookie policy to be added to Globe's Privacy Policy. 
- [X ] 📝 `docs` -- Documentation
=> feat: Update to privacy-policy on cookies

packages/globe_cli/lib/src/commands/build_logs_command.dart, packages/globe_cli/lib/src/commands/deploy_command.dart, packages/globe_cli/lib/src/utils/api.dart, packages/globe_cli/lib/src/utils/logs.dart
=> chore: CLI improvements

docs/releases/index.mdx, docs/releases/roadmap/ideas.mdx, docs/releases/roadmap/index.mdx, docs/releases/v/0.10.0mdx, docs/releases/v/0.11.0.mdx, docs/releases/v/0.12.0.mdx, docs/releases/v/0.3.0.mdx, docs/releases/v/0.4.0.mdx, docs/releases/v/0.6.0.mdx, docs/releases/v/0.7.0.mdx, docs/releases/v/0.8.0.mdx, docs/releases/v/0.9.0.mdx
Nov-Jan Release Notes
- Summary
- Individual pages
- [X ] 📝 `docs` -- Documentation
=> docs: Nov-Jan Release Notes

docs/terms-privacy/terms-of-service.mdx
Updated terms-of-service.mdx to clarify fair use policy. 
Documentation change only, no functional updates.
Related to dart_globe Issue #957.
=> docs: Add Fair Use Policy to Terms of Service (#957)

templates/crud_rest_api_shelf/.gitignore, templates/crud_rest_api_shelf/LICENSE, templates/crud_rest_api_shelf/TEMPLATE.md, templates/crud_rest_api_shelf/analysis_options.yaml, templates/crud_rest_api_shelf/bin/server.dart, templates/crud_rest_api_shelf/lib/data/repositories.dart, templates/crud_rest_api_shelf/lib/models/repository.dart, templates/crud_rest_api_shelf/lib/routes/repository_route.dart, templates/crud_rest_api_shelf/pubspec.yaml
Add new template for performing crud actions using Dart Shelf
=> feat: Add template for Shelf Server CRUD

docs/core-concepts/cron-jobs.mdx
Improved the Cron Jobs docs page to make it clear what is defined in the `globe.yaml` file for configuring cron jobs
=> docs: Improve the Cron Jobs docs page

templates/crud_rest_api_shelf/TEMPLATE.md, templates/crud_rest_api_shelf/bin/server.dart, templates/crud_rest_api_shelf/lib/routes/repository_route.dart, templates/crud_rest_api_shelf/pubspec.yaml
- Added get single repository route to complete the CRUD flow
- Added the CORS header to ensure the server is usable on the frontend
=> feat: Add Get Repository Route to crud_rest_api_shelf template

docs.json, docs/guides/dart-frog-deployment.mdx
=> docs: Add Dart Frog Deployment Guide

docs.json, docs/guides/index.mdx
=> docs: Add Dashboard Management guide

docs.json, docs/guides/add-custom-domain.mdx
=> docs: Add Custom Domain guide

docs.json, docs/guides/connect-flutter-app.mdx
=> docs: Add Connect Flutter App to Backend guide

docs.json
=> docs: Correct guide titles

packages/globe_cli/lib/src/utils/prompts.dart, packages/globe_cli/pubspec.yaml
=> chore: Ignore macOS, windows, linux and test directory

docs/guides/globe-cron-jobs.mdx
Closes https://github.com/invertase/dart_globe/issues/1038
=> docs: Add how to schedule Cron Jobs

docs.json, docs/guides/auth-email-verification.mdx, docs/guides/secure-dart-apis.mdx
=> docs: Add API Auth Security with Email Verification

docs/core-concepts/cron-jobs.mdx
=> docs: Update Cronjobs page to match feature changes

docs/releases/v/0.16.0.mdx
=> chore: Use new format for 0.16.0 release note

docs/frameworks/jaspr.mdx
Closes https://github.com/invertase/dart_globe/issues/1022
Closes https://github.com/invertase/dart_globe/issues/1086
=> docs: Update Jaspr docs to add support for all modes

docs.json, docs/core-concepts/cron-jobs.mdx, docs/core-concepts/github-integration.mdx, docs/core-concepts/globe-yaml.mdx, packages/globe_cli/test/workspace.dart
Related to: https://github.com/invertase/dart_globe/issues/1083
=> docs: Add the globe.yaml page in core concepts

docs/products/database/index.mdx
=> fix: Broken link

docs.json, docs/guides/serinus-backend-globe.mdx, packages/globe_cli/lib/src/package_info.dart, templates/crud_flutter_web/lib/main.dart, templates/crud_flutter_web/lib/src/new_repository_page.dart, templates/crud_flutter_web/lib/src/repository_page.dart
=> docs: Add guide for Serinus deployment

docs.json, docs/guides/build-notes-app.mdx
=> docs: Add Notes CRUD with Globe DB guide
