.github/.cspell/words_dictionary.txt
packages/globe_cli/lib/src/commands/deploy_command.dart
packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/pubspec.lock

Cli was showing the following error output on the deploy command in the latest version (0.0.1+1)
This PR fixes the bug
There was a missing state `deploying` that was added to the `DeploymentState` enum and log handling was also added.

fix(globe_cli): Bad state no element error on deployment fixed

---

packages/globe_cli/lib/src/commands/deploy_command.dart

It's currently broken since Juggler refactor

refactor: Remove logging streaming from CLI

---

docs/cli/commands/deploy.mdx
packages/globe_cli/lib/src/commands/deploy_command.dart

This PR re-enables realtime build logs, but makes this an opt-in feature (need to pass `--logs` to `globe deploy`)

feat(globe_cli): Add --logs for globe deploy

---

packages/globe_cli/lib/src/commands/deploy_command.dart

Resolves: https://github.com/invertase/dart_globe/issues/104
This PR shows `globe build-log` hint when deployment fails.
```shell
➜  shelf git:(feat/show-build-logs-hint) ✗ dart run ../../packages/globe_cli/bin/globe.dart deploy
✓ Deploying to codekeyz/zomato (2.9s)
✓ Deployment has been queued
🔍 View deployment: https://globe.dev/codekeyz/zomato/deployments/b7dd77ab-7ee6-4eb2-86cc-a7343704d70e
✓ Queued (7.0s)
✗ Deployment failed (43.7s)
Use globe build-logs --deployment="b7dd77ab-7ee6-4eb2-86cc-a7343704d70e" to view the build logs
```

feat(globe_cli): Show build-log hint when deployment fails

---

packages/globe_cli/lib/src/commands/login_command.dart
packages/globe_cli/lib/src/utils/open_url.dart
packages/globe_cli/test/login_test.dart

Added a line of text in the output of the login command to show the url that will be opened in the browser so that the user can manually login by going to the url. Closes #25

feat(globe_cli): Added login url in output of login command

---

docs/cli/commands/token.mdx
packages/globe_cli/lib/src/command_runner.dart
packages/globe_cli/lib/src/commands/commands.dart
packages/globe_cli/lib/src/commands/token/token_create_command.dart
packages/globe_cli/lib/src/commands/token/token_delete_command.dart
packages/globe_cli/lib/src/commands/token/token_list_command.dart
packages/globe_cli/lib/src/commands/token_command.dart
packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/prompts.dart

Resolves: https://github.com/invertase/dart_globe/issues/134

feat: Token create & delete from CLI

---

docs.yaml
docs/cli/commands/token.mdx
docs/cli/index.mdx

Add Token doc to the list of CLI commands

docs: Add token to list of cli commands

---

packages/globe_cli/lib/src/commands/token/token_create_command.dart
packages/globe_cli/lib/src/commands/token/token_delete_command.dart
packages/globe_cli/lib/src/commands/token/token_list_command.dart
packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/prompts.dart

Allow `globe token` commands to be run outside the scope of a globe project

fix: Remove need for scope validation

---

CHANGELOG.md
packages/globe_cli/CHANGELOG.md
packages/globe_cli/lib/src/package_info.dart
packages/globe_cli/lib/src/utils/archiver.dart
packages/globe_cli/pubspec.yaml

Fixes: https://discord.com/channels/1179425190007021568/1210461084352389240
On windows, I think the uploaded archive is empty due to the path separator being incorrect.

fix: Correctly handle windows path separators

---

packages/globe_cli/lib/src/commands/build_logs_command.dart
packages/globe_cli/lib/src/commands/deploy_command.dart
packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/logs.dart
packages/globe_cli/lib/src/utils/metadata.dart
packages/globe_cli/pubspec.lock
packages/globe_cli/pubspec.yaml

This PR brings back log streaming over WS

fix: Stream build logs over WS

---

packages/globe_cli/lib/src/utils/archiver.dart

Fixes issues where the patterns extracted from `.gitignore` files were over matching, for example: `**build**` matches `/some/path/my_build_file.dart`
This update better handles gitignore specs, along with adding in verbose logging to indicate what's going on.

fix: Improve archiver gitignore matching

---

docs/deployments/environment-variables.mdx

Update the environment variable docs to add more info. Add package info and available default variables.
Closes https://github.com/invertase/dart_globe/issues/212

docs: Updated environment variable docs

---

packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/prompts.dart

Add "All projects" option in a select projects prompt

refactor: Add select all projects option

---

packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/scope.dart

The CLI will give an error if the user tries to deploy paused project.
For the Project serialize logic, I added a new condition because in the near future we will refactor paused out of it and at that time it will not be a breaking change.

feat(globe_cli): Paused project handle for deploy and build log

---

examples/flutter_web/pubspec.lock
packages/globe_cli/lib/src/command.dart
packages/globe_cli/lib/src/command_runner.dart
packages/globe_cli/lib/src/commands/build_logs_command.dart
packages/globe_cli/lib/src/commands/deploy_command.dart
packages/globe_cli/lib/src/commands/project/project_pause_command.dart
packages/globe_cli/lib/src/commands/project/project_resume_command.dart
packages/globe_cli/lib/src/get_it.dart
packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/prompts.dart
packages/globe_cli/lib/src/utils/scope.dart
packages/globe_cli/pubspec.lock
packages/globe_cli/test/mock_helpers.dart
packages/globe_cli/test/mocks.dart
packages/globe_cli/test/project/project_resume_command_test.dart
templates/notes_app_shelf/frontend/pubspec.lock

This enables CIs to use `globe <command> --project=id --org=id` instead of having to use `globe link` first.

feat: Add `--project` and `--org` options on commands that depend on "scope".

---

packages/globe_cli/lib/src/command.dart
packages/globe_cli/lib/src/command_runner.dart
packages/globe_cli/lib/src/commands/deploy_command.dart
packages/globe_cli/lib/src/package_info.dart
packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/prompts.dart
packages/globe_cli/lib/src/utils/scope.dart

Allow `--token` to be parsed for all other commands, not just `deploy`.

chore: Make --token applicable to all other commands

---

packages/globe_tasks/lib/server.dart

Globe Cron Jobs expect URLs with `POST` method.

fix: Use POST method for cron routes

---

CHANGELOG.md
packages/globe_cli/CHANGELOG.md
packages/globe_cli/lib/src/package_info.dart
packages/globe_cli/pubspec.lock
packages/globe_cli/pubspec.yaml
packages/globe_tasks/pubspec.yaml

chore: Publish packages (release)

---

packages/globe_cli/lib/src/command_runner.dart
packages/globe_cli/lib/src/commands/build_logs_command.dart
packages/globe_cli/lib/src/commands/deploy_command.dart
packages/globe_cli/lib/src/commands/link_command.dart
packages/globe_cli/lib/src/commands/project/project_pause_command.dart
packages/globe_cli/lib/src/commands/project/project_resume_command.dart
packages/globe_cli/lib/src/commands/token/token_delete_command.dart
packages/globe_cli/lib/src/commands/token/token_list_command.dart
packages/globe_cli/lib/src/commands/unlink_command.dart
packages/globe_cli/lib/src/utils/api.dart
packages/globe_cli/lib/src/utils/prompts.dart
packages/globe_cli/lib/src/utils/scope.dart
packages/globe_cli/pubspec.lock
packages/globe_cli/pubspec.yaml

Closes: https://github.com/orgs/invertase/projects/23/views/1?pane=issue&itemId=54493236&issue=invertase%7Cdart_globe%7C97
This PR introduces the ability to link multiple projects within the same directory (e.g., mono-repos). By updating the `project.json` schema to support a list of `ScopeMetadata`, users can now link and manage multiple projects seamlessly.
```json
[
{
"orgId": "eecbc0fb-ee17-4d87-9b74-0ce33e1b7cf1",
"projectId": "bd239097-1b68-43e6-a887-466e4f786da3",
"projectSlug": "blog-backend-369d"
},
{
"orgId": "eecbc0fb-ee17-4d87-9b74-0ce33e1b7cf1",
"projectId": "2e8e0149-db61-4883-b734-4d6832824ca5",
"projectSlug": "blog-frontend"
}
]
```
- #### Multi-project linking
`globe link` command now supports linking multiple projects.
```sh
~/Projects/OpenSource/dart-blog | on main >1 …
```

feat: Multi project linking via CLI

---

packages/globe_cli/lib/src/utils/logs.dart
packages/globe_cli/lib/src/utils/prompts.dart

This fixes issue for mono-repos where `Globe CLI` is run from root directory, but project directory isn't root directory.
```
serverpod_project 
- serverpod_client
- serverpod_flutter
- serverpod_server (actual project directory)
```
Resolving main entry should return `bin/main.dart` instead of `serverpod_server/bin/main.dart` since `serverpod_server` is already our working directory.

fix: Resolve main entry path relative to project directory

---

docs/cli/commands/unlink.mdx

Documentation update using this PR info: https://github.com/invertase/globe/pull/117
- [X ] 📝 `docs` -- Documentation

docs: Unlinking multi projects update

---

docs/deployments/domains.mdx

- Updated domains.mdx to include custom domain details.
- Documentation change only, no functional updates.
- Related to dart_globe Issue [#955.](https://github.com/invertase/dart_globe/issues/955)

docs: Update domains page to include custom domain details

---

packages/globe_cli/lib/src/command_runner.dart
packages/globe_cli/lib/src/commands/runtime/runtime_install_command.dart
packages/globe_cli/lib/src/commands/runtime_command.dart

feat: Add simple globe runtime install
